CREATE TABLE PUBLIC.APP_CERT_MAPPING (
	ID CHARACTER VARYING(255) NOT NULL,
	APPLICATION_UUID CHARACTER VARYING(255),
	SERIAL_NUMBER CHARACTER VARYING(255),
	ISSUER_DN CHARACTER VARYING(255),
	ALIAS CHARACTER VARYING(255),
	THUMBPRINT CHARACTER VARYING(255),
	THUMBPRINTSHA256 CHARACTER VARYING(255),
	PDND_PUBLIC_KEY CHARACTER VARYING(2048),
	PDND_CLIENT_ID CHARACTER VARYING(255),
	PDND_PURPOSEID CHARACTER VARYING(255),
	ENABLED BOOLEAN,
	CONSTRAINT NEWTABLE_PK PRIMARY KEY (ID)
);

CREATE TABLE MODI_FRUIZIONE_SUBSCRIPTION (
	SUBSCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
	APPLICATION_UUID CHARACTER VARYING(256),
	TYP CHARACTER VARYING(256),
	ISS CHARACTER VARYING(256),
	SUB CHARACTER VARYING(256),
	AUD CHARACTER VARYING(256),
	PRIVATE_KEY_PEM CHARACTER LARGE OBJECT,
	PUBLIC_KEY_PEM CHARACTER LARGE OBJECT,
	CERTIFICATE_PEM CHARACTER LARGE OBJECT,
	ENABLED BOOLEAN,
	CONSTRAINT MODI_FRUIZIONE_SUBSCRIPTION_PK PRIMARY KEY (SUBSCRIPTION_ID)
);

CREATE TABLE PDND_FRUIZIONE_SUBSCRIPTION (
	SUBSCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
	APPLICATION_UUID CHARACTER VARYING(256),
	URI CHARACTER VARYING(256),
	KID CHARACTER VARYING(256),
	ALG CHARACTER VARYING(256),
	TYP CHARACTER VARYING(256),
	ISS CHARACTER VARYING(256),
	SUB CHARACTER VARYING(256),
	AUD CHARACTER VARYING(256),
	PURPOSE_ID CHARACTER VARYING(256),
	CLIENTID CHARACTER VARYING(255),
	"SCOPE" CHARACTER VARYING(255),
	PRIVATE_KEY_PEM CHARACTER LARGE OBJECT,
	ENABLED BOOLEAN,
	CONSTRAINT PDND_FRUIZIONE_SUBSCRIPTION_PK PRIMARY KEY (SUBSCRIPTION_ID)
);
