CREATE TABLE MODI_FRUIZIONE_SUBSCRIPTION_SOAP (
            SUBSCRIPTION_ID INTEGER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) NOT NULL,
            APPLICATION_UUID VARCHAR (255),
			WSADDRESSING_TO VARCHAR (255),
            PRIVATE_KEY_PEM VARCHAR (2048),
            CERTIFICATE_PEM VARCHAR (2048),
            ENABLED CHAR check (ENABLED in (0,1)),
            PRIMARY KEY (SUBSCRIPTION_ID)
);


CREATE TABLE APP_CERT_MAPPING_SOAP (
            ID VARCHAR (255) NOT NULL,
            APPLICATION_UUID VARCHAR (255),
            SERIAL_NUMBER VARCHAR (255),
            ISSUER_DN VARCHAR(255),
			ISSUER_NAME VARCHAR(255),
            ALIAS VARCHAR (255),
            THUMBPRINT VARCHAR (255),
            THUMBPRINTSHA256 VARCHAR (255),
            SUBJECT_KEY_IDENTIFIER VARCHAR (255),
            CERTIFICATE_PEM VARCHAR (2048),
            ENABLED CHAR check (ENABLED in (0,1)),
            PRIMARY KEY (ID)
);
